//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scenes/ControllerInteract.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControllerInteract : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControllerInteract()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControllerInteract"",
    ""maps"": [
        {
            ""name"": ""Interact"",
            ""id"": ""8a871e60-c9bc-425d-89d9-98a86d110304"",
            ""actions"": [
                {
                    ""name"": ""talk"",
                    ""type"": ""Button"",
                    ""id"": ""2ca2462c-d38a-4a44-9797-4def3fb7d503"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f7744929-1c84-4126-a47d-13211a875182"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""talk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Interact
        m_Interact = asset.FindActionMap("Interact", throwIfNotFound: true);
        m_Interact_talk = m_Interact.FindAction("talk", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Interact
    private readonly InputActionMap m_Interact;
    private IInteractActions m_InteractActionsCallbackInterface;
    private readonly InputAction m_Interact_talk;
    public struct InteractActions
    {
        private @ControllerInteract m_Wrapper;
        public InteractActions(@ControllerInteract wrapper) { m_Wrapper = wrapper; }
        public InputAction @talk => m_Wrapper.m_Interact_talk;
        public InputActionMap Get() { return m_Wrapper.m_Interact; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InteractActions set) { return set.Get(); }
        public void SetCallbacks(IInteractActions instance)
        {
            if (m_Wrapper.m_InteractActionsCallbackInterface != null)
            {
                @talk.started -= m_Wrapper.m_InteractActionsCallbackInterface.OnTalk;
                @talk.performed -= m_Wrapper.m_InteractActionsCallbackInterface.OnTalk;
                @talk.canceled -= m_Wrapper.m_InteractActionsCallbackInterface.OnTalk;
            }
            m_Wrapper.m_InteractActionsCallbackInterface = instance;
            if (instance != null)
            {
                @talk.started += instance.OnTalk;
                @talk.performed += instance.OnTalk;
                @talk.canceled += instance.OnTalk;
            }
        }
    }
    public InteractActions @Interact => new InteractActions(this);
    public interface IInteractActions
    {
        void OnTalk(InputAction.CallbackContext context);
    }
}
